language: generic

cache:
  directories:
    - ${STACK_HOME}

before_install:
  - mkdir -p ${STACK_BIN}
  - export PATH=${STACK_BIN}:$PATH
  - travis_retry curl -sSL https://get.haskellstack.org/ | sh

script:
  - stack install

jobs:
  include:
    - os: linux
      env:
        - STACK_HOME=${HOME}/.stack
        - STACK_BIN=${HOME}/.local/bin
      before_deploy:
        - cp ${STACK_BIN}/unfog ${STACK_BIN}/unfog-${TRAVIS_OS_NAME}
      deploy: &deploy_base
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file: ${STACK_BIN}/unfog-${TRAVIS_OS_NAME}
        skip_cleanup: true
        draft: false
        name: ${TRAVIS_TAG}
        on:
          tags: true

    - os: osx
      env:
        - STACK_HOME=${HOME}/.stack
        - STACK_BIN=${HOME}/.local/bin
      before_deploy:
        - cp ${STACK_BIN}/unfog ${STACK_BIN}/unfog-${TRAVIS_OS_NAME}
      deploy:
        <<: *deploy_base

    - os: windows
      env:
        - STACK_HOME=${HOME}/AppData/Roaming/stack
        - STACK_BIN=${HOME}/AppData/Roaming/local/bin
      before_deploy:
        - cp ${STACK_BIN}/unfog.exe ${STACK_BIN}/unfog-${TRAVIS_OS_NAME}
      deploy:
        <<: *deploy_base
