name:                unfog
version:             0.1.0.0
github:              "soywod/unfog"
license:             BSD3
author:              "Clément DOUIN"
maintainer:          "clement.douin@posteo.net"
copyright:           "2019 Clément DOUIN"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/unfog#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - directory
  - time
  - boxes
  - human-readable-duration
  - aeson
  - bytestring
  - base-compat

executables:
  unfog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unfog

tests:
  unfog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unfog
